pipeline {

    agent any

    tools {
        maven "mvn-3.6"
        jdk "jdk-13"
    }

    environment {
        COMMIT_AUTHOR = ""
        COMMIT_MESSAGE = ""
        PROJECT_VERSION = ""
    }

    stages {
        stage("Setting environment") {
            steps {
                script {
                    pom = readMavenPom file:"pom.xml"
                    PROJECT_VERSION = pom.version
                    COMMIT_MESSAGE = sh script: "git show -s --pretty='%s'", returnStdout: true
                    COMMIT_AUTHOR = sh script: "git show -s --pretty='%cn <%ce>'", returnStdout: true
                    COMMIT_AUTHOR = COMMIT_AUTHOR.trim()
                }
            }
        }
        stage("Run tests") {
            steps {
                sh "mvn clean test"
            }
        }
        stage("Deploy library") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-username', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh "mvn clean deploy -Dci.nexus.user=$USERNAME -Dci.nexus.pass=$PASSWORD --settings .ci/settings.xml -DskipTests=true"
                }
            }
        }
    }
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n'${COMMIT_MESSAGE}' from ${COMMIT_AUTHOR}")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n$'{COMMIT_MESSAGE}' from ${COMMIT_AUTHOR}")
        }
    }
}